export { detectPlatform, isElectronHost, isDaemonBackedHost, type CodesurfPlatform } from './detect'
export { resolveHostBase, hostUrl } from './hostConfig'
export { installHostBridge, type InstallResult } from './installHostBridge'
export { createDaemonBackedElectronApi } from './daemonBridge'
export { pickProjectFolderPath, type PickFolderResult } from './pickFolder'
export { registerCodesurfPwa, applyPwaUpdate, isPwaDisplayMode } from './pwa'
