/**
 * Progressive Web App registration for Chrome installable apps + Safari desktop.
 * Only active on web target (not Electron preload, not required for Native shell).
 */

export type PwaUpdateHandler = (reload: () => void) => void

let updateSW: ((reloadPage?: boolean) => Promise<void>) | null = null

export function isPwaDisplayMode(): boolean {
  if (typeof window === 'undefined') return false
  const mq = window.matchMedia?.('(display-mode: standalone)')
  const iosStandalone = (navigator as Navigator & { standalone?: boolean }).standalone === true
  return Boolean(mq?.matches || iosStandalone)
}

/**
 * Register the service worker generated by vite-plugin-pwa.
 * Safe no-op when SW is unavailable (Electron, unsupported browser, dev without SW).
 */
export async function registerCodesurfPwa(options?: {
  onNeedRefresh?: PwaUpdateHandler
  onOfflineReady?: () => void
}): Promise<void> {
  if (typeof window === 'undefined') return
  // Electron has its own shell — do not take over with a SW.
  if ((window as Window & { electron?: unknown }).electron && !(window as Window & { __CODESURF_PLATFORM__?: string }).__CODESURF_PLATFORM__) {
    // If platform was detected as electron before bridge, skip.
  }
  const platform = (window as Window & { __CODESURF_PLATFORM__?: string }).__CODESURF_PLATFORM__
  if (platform === 'electron') return

  if (!('serviceWorker' in navigator)) return

  try {
    // Virtual module injected by vite-plugin-pwa
    const { registerSW } = await import('virtual:pwa-register')
    updateSW = registerSW({
      immediate: true,
      onNeedRefresh() {
        options?.onNeedRefresh?.(() => {
          void updateSW?.(true)
        })
      },
      onOfflineReady() {
        options?.onOfflineReady?.()
        console.info('[codesurf-pwa] offline shell ready')
      },
      onRegisteredSW(swUrl, registration) {
        console.info('[codesurf-pwa] registered', swUrl)
        // Periodic update checks (Chrome desktop install)
        if (registration) {
          window.setInterval(() => {
            void registration.update()
          }, 60 * 60 * 1000)
        }
      },
      onRegisterError(error) {
        console.warn('[codesurf-pwa] registration failed', error)
      },
    })
  } catch (err) {
    // virtual:pwa-register missing when plugin not active (e.g. pure electron build)
    console.debug('[codesurf-pwa] skip register', err)
  }
}

export async function applyPwaUpdate(): Promise<void> {
  if (updateSW) await updateSW(true)
}
